import type { ReviewerRole } from "./interfaces"

export function emptyReviewerOutput(reviewer: ReviewerRole, reason: string) {
  return {
    version: 1,
    reviewer,
    trigger_reason: reason,
    verdict: "pass" as const,
    findings: [],
    score: 100,
    block_completion: false,
    next_actions: [],
    evidence_confidence: 100,
    ts: new Date().toISOString(),
  }
}

export function buildReviewerPrompt(input: {
  reviewer: ReviewerRole
  reason: string
  compactContext: string
  effectiveModel: string
}) {
  const header = [
    `[dll-agent supervisor auto-trigger]`,
    `<compact-review-context>`,
    input.compactContext,
    `</compact-review-context>`,
    ``,
  ]
  const json = (reviewer: ReviewerRole) => [
    `\`\`\`json`,
    JSON.stringify(emptyReviewerOutput(reviewer, input.reason), null, 2),
    `\`\`\``,
  ]

  const prompts: Record<ReviewerRole, string[]> = {
    "requirements-inspector": [
      ...header,
      `Act as the requirements inspector (${input.effectiveModel}). Check:`,
      `1. Is the current work still aligned with the user's original Chinese intent?`,
      `2. Are there any contradictions, phase drift, or rule violations?`,
      `3. Are all important claims backed by evidence?`,
      ``,
      `ROLE BOUNDARY: use the compact context first. Only read listed relevant files when needed. Do not scan the whole repo.`,
      `The runtime enforces this reviewer as read-only; bash/edit/web/task tools are denied.`,
      `Finish promptly and emit the JSON verdict.`,
      ``,
      `IMPORTANT: Output your findings in this exact machine-readable JSON format:`,
      ...json("requirements-inspector"),
      ``,
      `Cite precise evidence. If you find blockers, set "block_completion": true and add findings with severity "block".`,
    ],
    "long-context-archivist": [
      ...header,
      `Act as the long-context archivist (${input.effectiveModel}). Check:`,
      `1. Are there logs, documents, baselines, or phase history that have been lost or misread?`,
      `2. Is the conversation context coherent across the full session?`,
      `3. Are there missing pieces of evidence from earlier phases?`,
      ``,
      `ROLE BOUNDARY: use the compact context first. Only read listed relevant files/logs when needed. Do not scan the whole repo.`,
      `The runtime enforces this reviewer as read-only; bash/edit/web/task tools are denied.`,
      `Finish promptly and emit the JSON verdict.`,
      ``,
      `IMPORTANT: Output in machine-readable JSON format as shown.`,
      ...json("long-context-archivist"),
    ],
    "chief-engineer": [
      ...header,
      `Act as the chief engineer (${input.effectiveModel}). Diagnose the tool failures:`,
      `1. What is the root cause of the failures?`,
      `2. Can the failures be fixed with a different approach, tool, or permission?`,
      `3. Is the current task approach fundamentally broken?`,
      ``,
      `Propose actionable engineering fixes with exact commands/paths.`,
      `Output in machine-readable JSON format as shown.`,
    ],
    "final-auditor": [
      ...header,
      `Act as the on-demand strategic/final auditor (${input.effectiveModel}). Check:`,
      `1. Is the user goal truly complete?`,
      `2. Is there sufficient evidence for the completion claim?`,
      `3. Are there outstanding engineering risks or unverified claims?`,
      `4. Is the strategic direction still sound?`,
      ``,
      `ROLE BOUNDARY: this is a read-only audit. Do not run commands, edit files, patch files, or create subtasks.`,
      `The runtime enforces this reviewer as read-only; write/exec/task tools are denied.`,
      ``,
      `Output in machine-readable JSON format as shown.`,
      ...json("final-auditor"),
    ],
    "role-cross": [
      ...header,
      `Run a temporary role-crossing review (${input.effectiveModel}). Inspect the problem from a different role's perspective:`,
      `1. Find blind spots that the current role may have missed.`,
      `2. Identify missing evidence.`,
      `3. Propose actionable recovery steps.`,
      ``,
      `This role crossing ends after this review round. Output in machine-readable JSON format.`,
      ...json("role-cross"),
    ],
    "task-completion-archivist": [
      ...header,
      `Act as the task-completion-archivist (${input.effectiveModel}). Check whether the task is truly complete:`,
      `1. Is the user goal fully achieved?`,
      `2. Are there blocking unfinished items in the completion report?`,
      `3. Classify ALL unfinished items as: blocking_unfinished | non_blocking_followup | requires_user_input`,
      `4. If blocking items exist, generate a continuation packet with a next_execution_plan.`,
      `5. Never mark as VERIFIED_COMPLETE if blocking unfinished items exist.`,
      ``,
      `ROLE BOUNDARY: use the compact context first. Only read listed relevant files when needed.`,
      `The runtime enforces this reviewer as read-only; bash/edit/web/task tools are denied.`,
      `Output a CONTINUATION PACKET in the following JSON format:`,
      `\`\`\`json`,
      JSON.stringify({
        version: 1,
        reviewer: "task-completion-archivist",
        trigger_reason: input.reason,
        verdict: "pass",
        completion_status: "UNVERIFIED_COMPLETE",
        blocking_unfinished: [],
        non_blocking_followup: [],
        requires_user_input: [],
        already_completed: [],
        next_execution_plan: [],
        allow_final_report: false,
        findings: [],
        score: 100,
        block_completion: false,
        next_actions: [],
        evidence_confidence: 100,
        ts: new Date().toISOString(),
      }, null, 2),
      `\`\`\``,
    ],
    "multimodal-context-interpreter": [
      ...header,
      `Act as the multimodal context interpreter (${input.effectiveModel}). Your role is to analyze non-text inputs:`,
      `1. Identify all non-text inputs (screenshots, images, webpage visuals, PPT figures, flowcharts, charts, video, audio)`,
      `2. Extract observations: text content, visual layout, structure, errors, warnings, important details`,
      `3. Assign confidence (low/medium/high) to each observation`,
      `4. Set context_sufficient=false if the input is too ambiguous`,
      `5. NEVER claim high confidence if uncertainties remain`,
      ``,
      `ROLE BOUNDARY: read-only analysis. Do not modify files, run code, or make engineering decisions.`,
      `The runtime enforces this reviewer as read-only; bash/edit/task tools are denied.`,
      `Output a structured multimodal_context_packet using the schema from multimodal-context.ts.`,
      ``,
      `IMPORTANT: Output in this JSON format:`,
      `\`\`\`json`,
      JSON.stringify({
        packet_type: "multimodal_context_packet",
        packet_id: "mmctx_placeholder",
        source_hash: "auto-generated",
        role: "multimodal-context-interpreter",
        model: input.effectiveModel,
        input_type: "screenshot",
        user_goal: input.reason,
        source_ref: "",
        task_relevance: "",
        observations: [],
        detected_text: null,
        visual_structure: null,
        errors_or_warnings: [],
        important_details: [],
        uncertainties: [],
        overall_confidence: "medium",
        context_sufficient: true,
        recommended_next_role: null,
        evidence_refs: [],
        redaction_status: "none",
        created_at: new Date().toISOString(),
      }, null, 2),
      `\`\`\``,
    ],
  }
  return prompts[input.reviewer].join("\n")
}

export * as ReviewerPromptTemplates from "./reviewer-prompt-templates"
